-- Clear existing test data with proper UUID casting
DELETE FROM public.buildings WHERE code IN ('001', '002', '003', '004', '005', '006', '007', '008', '009', '010');
DELETE FROM public.suppliers WHERE name IN ('Tech Solutions Lda', 'Construtora Silva', 'Eletricista João', 'Canalizador Manuel', 'Serralheiro Pedro', 'Elevadores Lisboa', 'Limpezas Express', 'Jardinagem Verde', 'Segurança Total', 'Obras & Reparações', 'Pinturas Modernas');
DELETE FROM public.intervention_types WHERE name IN ('Reparação Geral', 'Manutenção Preventiva', 'Limpeza', 'Jardinagem', 'Eletricidade', 'Canalização', 'Pintura', 'Serralharia', 'Elevadores', 'Segurança', 'Construção Civil', 'Outros', 'Emergência', 'Garantia');

-- Insert real building data (74 buildings)
INSERT INTO public.buildings (code, name, address, nif, cadastral_code, is_active, admin_notes) VALUES
('003', 'COND. R. ALEXANDRE HERCULANO,Nº35', 'R. ALEXANDRE HERCULANO, Nº35', '', '', true, ''),
('004', 'COND. TRAVESSA CONDE DA RIBEIRA, Nº12', 'TRAVESSA CONDE DA RIBEIRA, Nº12', '', '', true, ''),
('006', 'COND.R.NOSSA SRA DA ANUNCIAÇÃO Nº5', 'R.NOSSA SRA DA ANUNCIAÇÃO Nº5', '', '', true, ''),
('008', 'COND. R.VITORINO NEMÉSIO, 8', 'R.VITORINO NEMÉSIO, 8', '', '', true, ''),
('009', 'COND. R. DAS ORQUÍDEAS, Nº1', 'R. DAS ORQUÍDEAS, Nº1', '', '', true, ''),
('010', 'COND. RUA BEATRIZ COSTA Nº 4', 'RUA BEATRIZ COSTA Nº 4', '', '', true, ''),
('017', 'COND. RUA CORREIA GARÇÃO, Nº 11', 'RUA CORREIA GARÇÃO, Nº 11', '', '', true, ''),
('029', 'COND. RUA MAJOR MOUZINHO ALBUQUERQUE LT.12A', 'RUA MAJOR MOUZINHO ALBUQUERQUE LT.12A', '', '', true, ''),
('031', 'COND AV. DAS DESCOBERTAS, 41', 'AV. DAS DESCOBERTAS, 41', '', '', true, ''),
('035', 'COND. RUA CÂNDIDO DE OLIVEIRA, 13', 'RUA CÂNDIDO DE OLIVEIRA, 13', '', '', true, ''),
('045', 'COND PRCT. DAVID MOURÃO FERREIRA, Nº. 2', 'PRCT. DAVID MOURÃO FERREIRA, Nº. 2', '', '', true, ''),
('055', 'COND PROF. DR. FRANCISCO GENTIL LOTE A', 'PROF. DR. FRANCISCO GENTIL LOTE A', '', '', true, ''),
('059', 'COND. RUA ANTERO DE QUENTAL, LOTE 24-A', 'RUA ANTERO DE QUENTAL, LOTE 24-A', '', '', true, ''),
('064', 'COND PRACETA DAS URMEIRAS,3', 'PRACETA DAS URMEIRAS,3', '', '', true, ''),
('067', 'COND PRACETA DA MINA,2', 'PRACETA DA MINA,2', '', '', true, ''),
('072', 'COND. RUA ALZIRA BEATRIZ PACHECO 2', 'RUA ALZIRA BEATRIZ PACHECO 2', '', '', true, ''),
('074', 'COND. RUA ALZIRA BEATRIZ PACHECO,14', 'RUA ALZIRA BEATRIZ PACHECO,14', '', '', true, ''),
('077', 'COND RUA DA MEMÓRIA, Nº. 29', 'RUA DA MEMÓRIA, Nº. 29', '', '', true, ''),
('078', 'COND RUA DA MEMÓRIA, Nº 27', 'RUA DA MEMÓRIA, Nº 27', '', '', true, ''),
('080', 'COND PRACETA PEDRO MANUEL PEREIRA Nº 6', 'PRACETA PEDRO MANUEL PEREIRA Nº 6', '', '', true, ''),
('082', 'COND.AV. PROF. DR. AUGUSTO ABREU LOPES, 49', 'AV. PROF. DR. AUGUSTO ABREU LOPES, 49', '', '', true, ''),
('083', 'COND PRT ANTÓNIO CORTE REAL, TORRE 3', 'PRT ANTÓNIO CORTE REAL, TORRE 3', '', '', true, ''),
('086', 'COND PCTA. CAMILO PESSANHA, Nº 4', 'PCTA. CAMILO PESSANHA, Nº 4', '', '', true, ''),
('089', 'COND RUA MALUDA, Nº 8, 10 E 12', 'RUA MALUDA, Nº 8, 10 E 12', '', '', true, ''),
('092', 'COND RUA ALVES REDOL, 11', 'RUA ALVES REDOL, 11', '', '', true, ''),
('093', 'COND. RUA VALE FORMOSO DE CIMA, 119', 'RUA VALE FORMOSO DE CIMA, 119', '', '', true, ''),
('098', 'COND. RUA 4 DE OUTUBRO, Nº. 9', 'RUA 4 DE OUTUBRO, Nº. 9', '', '', true, ''),
('100', 'COND. RUA ALMEIDA GARRETT, Nº. 2', 'RUA ALMEIDA GARRETT, Nº. 2', '', '', true, ''),
('101', 'COND. RUA D. AFONSO HENRIQUES, 9', 'RUA D. AFONSO HENRIQUES, 9', '', '', true, ''),
('108', 'COND. RUA ALZIRA BEATRIZ PACHECO, 16', 'RUA ALZIRA BEATRIZ PACHECO, 16', '', '', true, ''),
('110', 'COND. RUA ANTÓNIO SÉRGIO, Nº 4', 'RUA ANTÓNIO SÉRGIO, Nº 4', '', '', true, ''),
('121', 'COND. R. BEATRIZ ÂNGELO, Nº 10', 'R. BEATRIZ ÂNGELO, Nº 10', '', '', true, ''),
('122', 'AV PROFESSOR DR. AUGUSTO ABREU LOPES Nº61', 'AV PROFESSOR DR. AUGUSTO ABREU LOPES Nº61', '', '', true, ''),
('123', 'COND. AV. DAS DESCOBERTAS, 31', 'AV. DAS DESCOBERTAS, 31', '', '', true, ''),
('126', 'COND. RUA VALE FORMOSO DE CIMA, 113', 'RUA VALE FORMOSO DE CIMA, 113', '', '', true, ''),
('128', 'COND. RUA DR. JAIME CORTESÃO, 15', 'RUA DR. JAIME CORTESÃO, 15', '', '', true, ''),
('140', 'COND. RUA AQUILINO RIBEIRO, 3', 'RUA AQUILINO RIBEIRO, 3', '', '', true, ''),
('141', 'COND. PCTA JOÃO VILLARET Nº 1', 'PCTA JOÃO VILLARET Nº 1', '', '', true, ''),
('142', 'COND. RUA BARTOLOMEU DIAS, 13', 'RUA BARTOLOMEU DIAS, 13', '', '', true, ''),
('143', 'COND. RUA ANTONIO SERGIO, 8', 'RUA ANTONIO SERGIO, 8', '', '', true, ''),
('144', 'COND. R. DOMINGOS SEQUEIRA, 7', 'R. DOMINGOS SEQUEIRA, 7', '', '', true, ''),
('145', 'COND. R.VALE FORMOSO DE CIMA, 97', 'R.VALE FORMOSO DE CIMA, 97', '', '', true, ''),
('146', 'COND. PRACETA TEN. CORONEL SALGUEIRO MAIA, 8', 'PRACETA TEN. CORONEL SALGUEIRO MAIA, 8', '', '', true, ''),
('147', 'COND. RUA EUGÉNIO DE CASTRO, 6', 'RUA EUGÉNIO DE CASTRO, 6', '', '', true, ''),
('148', 'COND. PRACETA MARIA LAMAS, LT 47', 'PRACETA MARIA LAMAS, LT 47', '', '', true, ''),
('149', 'COND. RUA. DR. MARIO SACRAMENTO, 13', 'RUA. DR. MARIO SACRAMENTO, 13', '', '', true, ''),
('150', 'COND. R. PROFESSOR EGAS MONIZ, 32', 'R. PROFESSOR EGAS MONIZ, 32', '', '', true, ''),
('151', 'COND. R. MESTRE AVIZ, 16', 'R. MESTRE AVIZ, 16', '', '', true, ''),
('152', 'COND. PRAÇA PAIVA COUCEIRO, 5', 'PRAÇA PAIVA COUCEIRO, 5', '', '', true, ''),
('153', 'COND. PRACETA FLORBELA ESPANCA, 9', 'PRACETA FLORBELA ESPANCA, 9', '', '', true, ''),
('154', 'COND. CALÇADA DA PALMA DE BAIXO, 29', 'CALÇADA DA PALMA DE BAIXO, 29', '', '', true, ''),
('155', 'COND. RUA D. AFONSO HENRIQUES, 33', 'RUA D. AFONSO HENRIQUES, 33', '', '', true, ''),
('157', 'COND. RUA DOS OPERÁRIOS, Nº9', 'RUA DOS OPERÁRIOS, Nº9', '', '', true, ''),
('158', 'COND. AV.PROF. EGAS MONIZ, 9', 'AV.PROF. EGAS MONIZ, 9', '', '', true, ''),
('159', 'COND. AV. DEFENSORES DE CHAVES, Nº43', 'AV. DEFENSORES DE CHAVES, Nº43', '', '', true, ''),
('161', 'COND. RUA PADRE AMÉRICO, 12', 'RUA PADRE AMÉRICO, 12', '', '', true, ''),
('162', 'COND. RUA VALE FORMOSO DE CIMA, 134', 'RUA VALE FORMOSO DE CIMA, 134', '', '', true, ''),
('163', 'COND. R. PEDRO ÁLVARES CABRAL, 1', 'R. PEDRO ÁLVARES CABRAL, 1', '', '', true, ''),
('164', 'COND. RUA CABO VERDE, 14', 'RUA CABO VERDE, 14', '', '', true, ''),
('165', 'COND. AV. DAS ACÁCIAS, 2', 'AV. DAS ACÁCIAS, 2', '', '', true, ''),
('166', 'COND. PRACETA FLORBELA ESPANCA, 7', 'PRACETA FLORBELA ESPANCA, 7', '', '', true, ''),
('168', 'COND. R. DA JUVENTUDE, 11', 'R. DA JUVENTUDE, 11', '', '', true, ''),
('169', 'COND. RUA NUNO ALVARES PEREIRA, 7', 'RUA NUNO ALVARES PEREIRA, 7', '', '', true, ''),
('170', 'COND. R. CHAFARIZ DEL REI, 3', 'R. CHAFARIZ DEL REI, 3', '', '', true, ''),
('171', 'COND. R. VÍTOR CORDON, 1', 'R. VÍTOR CORDON, 1', '', '', true, ''),
('172', 'COND. AV.DAS ACÁCIAS, 10', 'AV.DAS ACÁCIAS, 10', '', '', true, ''),
('173', 'COND. R. DOS OPERÁRIOS, 11', 'R. DOS OPERÁRIOS, 11', '', '', true, ''),
('174', 'COND. AV. ELIAS GARCIA, 18', 'AV. ELIAS GARCIA, 18', '', '', true, ''),
('175', 'COND. R.AGOSTINHO SILVA, 10', 'R.AGOSTINHO SILVA, 10', '', '', true, ''),
('176', 'COND.R.PADRE JOSE ANCHIETA, 4', 'R.PADRE JOSE ANCHIETA, 4', '', '', true, ''),
('177', 'COND. RUA VALE FORMOSO DE CIMA, 127', 'RUA VALE FORMOSO DE CIMA, 127', '', '', true, ''),
('178', 'COND. PCTA VIRGÍNIA DE CASTRO ALMEIDA,3', 'PCTA VIRGÍNIA DE CASTRO ALMEIDA,3', '', '', true, ''),
('179', 'COND. RUA CMD SACADURA CABRAL, 11', 'RUA CMD SACADURA CABRAL, 11', '', '', true, ''),
('180', 'COND. PCTA FLORBELA ESPANCA, 2', 'PCTA FLORBELA ESPANCA, 2', '', '', true, '');

-- Clean up duplicate suppliers and keep only real ones
DELETE FROM public.suppliers WHERE name NOT IN ('TKE', 'Clefta', 'Sr. Obras', 'Mestre das Chaves', 'Desinfest Lar', 'Ascenso Eleva Lda', 'Ipest', 'Andre', 'bilal machraa');

-- Insert real intervention types data
INSERT INTO public.intervention_types (name, description, category, urgency_level) VALUES
('Reparação de Fugas de Água (Partes Comuns)', 'Canalização / Hidráulica', 'Canalização', 'urgent'),
('Desentupimento de Esgotos (Partes Comuns)', 'Canalização / Hidráulica', 'Canalização', 'urgent'),
('Manutenção de Bombas de Água / Grupo Hidropressor', 'Canalização / Hidráulica', 'Canalização', 'normal'),
('Reparação/Substituição Coluna de Água', 'Canalização / Hidráulica', 'Canalização', 'urgent'),
('Leitura/Verificação de Contadores', 'Canalização / Hidráulica', 'Canalização', 'normal'),
('Reparação de Avaria Elétrica (Partes Comuns)', 'Eletricidade', 'Eletricidade', 'urgent'),
('Substituição de Lâmpadas/Iluminação (Partes Comuns)', 'Eletricidade', 'Eletricidade', 'normal'),
('Manutenção Quadro Elétrico Geral', 'Eletricidade', 'Eletricidade', 'normal'),
('Reparação/Manutenção Videoporteiro/Intercomunicador', 'Eletricidade', 'Eletricidade', 'normal'),
('Reparação de Fissuras/Infiltrações (Partes Comuns)', 'Construção Civil / Pedreiro', 'Construção Civil', 'urgent'),
('Impermeabilização (Terraços, Coberturas, Garagens)', 'Construção Civil / Pedreiro', 'Construção Civil', 'normal'),
('Reparação de Pavimentos (Partes Comuns)', 'Construção Civil / Pedreiro', 'Construção Civil', 'normal'),
('Pequenas Obras de Conservação', 'Construção Civil / Pedreiro', 'Construção Civil', 'normal'),
('Pintura de Áreas Comuns (Escadas, Halls)', 'Pinturas', 'Pinturas', 'normal'),
('Pintura de Fachada', 'Pinturas', 'Pinturas', 'normal'),
('Pintura de Portas/Grades Comuns', 'Pinturas', 'Pinturas', 'normal'),
('Reparação/Manutenção Portão de Garagem', 'Serralharia / Automatismos', 'Serralharia', 'urgent'),
('Reparação/Substituição de Fechaduras (Portas Comuns)', 'Serralharia / Automatismos', 'Serralharia', 'urgent'),
('Reparação de Grades/Corrimãos', 'Serralharia / Automatismos', 'Serralharia', 'normal'),
('Manutenção Preventiva de Elevador', 'Elevadores', 'Elevadores', 'normal'),
('Reparação de Avaria de Elevador', 'Elevadores', 'Elevadores', 'urgent'),
('Manutenção de Jardins e Espaços Verdes', 'Jardinagem', 'Jardinagem', 'normal'),
('Manutenção/Reparação Sistema de Rega', 'Jardinagem', 'Jardinagem', 'normal'),
('Limpeza Geral de Áreas Comuns', 'Limpeza', 'Limpeza', 'normal'),
('Limpeza de Garagens', 'Limpeza', 'Limpeza', 'normal'),
('Limpeza de Vidros', 'Limpeza', 'Limpeza', 'normal'),
('Manutenção/Carregamento de Extintores', 'Segurança e Incêndio', 'Segurança', 'normal'),
('Manutenção Sistema Deteção Incêndios (SADI)', 'Segurança e Incêndio', 'Segurança', 'normal'),
('Manutenção Portas Corta-Fogo', 'Segurança e Incêndio', 'Segurança', 'normal'),
('Manutenção/Reparação CCTV', 'Segurança e Incêndio', 'Segurança', 'normal'),
('Controlo de Pragas', 'Outros', 'Outros', 'normal'),
('Limpeza de Caleiras/Algerozes', 'Outros', 'Outros', 'normal'),
('Verificação/Reparação Antena Coletiva', 'Outros', 'Outros', 'normal'),
('Pedido de Orçamento', 'Administrativos/Processuais', 'Administrativos', 'normal'),
('Ativação de Garantia', 'Administrativos/Processuais', 'Administrativos', 'normal'),
('outros', 'Outros', 'Outros', 'normal'),
('Manutenção Preventiva', 'Manutenção preventiva regular', 'Manutenção', 'normal'),
('Reparação de Emergência', 'Reparação urgente necessária', 'Emergência', 'urgent'),
('Instalação', 'Instalação de novos equipamentos', 'Instalação', 'normal');