-- First, clear existing test data
DELETE FROM public.buildings WHERE code IN ('001', '002', '003', '004', '005', '006', '007', '008', '009', '010');
DELETE FROM public.suppliers WHERE id IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21);
DELETE FROM public.intervention_types WHERE id IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14);

-- Insert real building data (74 buildings)
INSERT INTO public.buildings (id, code, name, address, nif, cadastral_code, is_active, admin_notes) VALUES
(gen_random_uuid(), '003', 'COND. R. ALEXANDRE HERCULANO,Nº35', 'R. ALEXANDRE HERCULANO, Nº35', '', '', true, ''),
(gen_random_uuid(), '004', 'COND. TRAVESSA CONDE DA RIBEIRA, Nº12', 'TRAVESSA CONDE DA RIBEIRA, Nº12', '', '', true, ''),
(gen_random_uuid(), '006', 'COND.R.NOSSA SRA DA ANUNCIAÇÃO Nº5', 'R.NOSSA SRA DA ANUNCIAÇÃO Nº5', '', '', true, ''),
(gen_random_uuid(), '008', 'COND. R.VITORINO NEMÉSIO, 8', 'R.VITORINO NEMÉSIO, 8', '', '', true, ''),
(gen_random_uuid(), '009', 'COND. R. DAS ORQUÍDEAS, Nº1', 'R. DAS ORQUÍDEAS, Nº1', '', '', true, ''),
(gen_random_uuid(), '010', 'COND. RUA BEATRIZ COSTA Nº 4', 'RUA BEATRIZ COSTA Nº 4', '', '', true, ''),
(gen_random_uuid(), '017', 'COND. RUA CORREIA GARÇÃO, Nº 11', 'RUA CORREIA GARÇÃO, Nº 11', '', '', true, ''),
(gen_random_uuid(), '029', 'COND. RUA MAJOR MOUZINHO ALBUQUERQUE LT.12A', 'RUA MAJOR MOUZINHO ALBUQUERQUE LT.12A', '', '', true, ''),
(gen_random_uuid(), '031', 'COND AV. DAS DESCOBERTAS, 41', 'AV. DAS DESCOBERTAS, 41', '', '', true, ''),
(gen_random_uuid(), '035', 'COND. RUA CÂNDIDO DE OLIVEIRA, 13', 'RUA CÂNDIDO DE OLIVEIRA, 13', '', '', true, ''),
(gen_random_uuid(), '045', 'COND PRCT. DAVID MOURÃO FERREIRA, Nº. 2', 'PRCT. DAVID MOURÃO FERREIRA, Nº. 2', '', '', true, ''),
(gen_random_uuid(), '055', 'COND PROF. DR. FRANCISCO GENTIL LOTE A', 'PROF. DR. FRANCISCO GENTIL LOTE A', '', '', true, ''),
(gen_random_uuid(), '059', 'COND. RUA ANTERO DE QUENTAL, LOTE 24-A', 'RUA ANTERO DE QUENTAL, LOTE 24-A', '', '', true, ''),
(gen_random_uuid(), '064', 'COND PRACETA DAS URMEIRAS,3', 'PRACETA DAS URMEIRAS,3', '', '', true, ''),
(gen_random_uuid(), '067', 'COND PRACETA DA MINA,2', 'PRACETA DA MINA,2', '', '', true, ''),
(gen_random_uuid(), '072', 'COND. RUA ALZIRA BEATRIZ PACHECO 2', 'RUA ALZIRA BEATRIZ PACHECO 2', '', '', true, ''),
(gen_random_uuid(), '074', 'COND. RUA ALZIRA BEATRIZ PACHECO,14', 'RUA ALZIRA BEATRIZ PACHECO,14', '', '', true, ''),
(gen_random_uuid(), '077', 'COND RUA DA MEMÓRIA, Nº. 29', 'RUA DA MEMÓRIA, Nº. 29', '', '', true, ''),
(gen_random_uuid(), '078', 'COND RUA DA MEMÓRIA, Nº 27', 'RUA DA MEMÓRIA, Nº 27', '', '', true, ''),
(gen_random_uuid(), '080', 'COND PRACETA PEDRO MANUEL PEREIRA Nº 6', 'PRACETA PEDRO MANUEL PEREIRA Nº 6', '', '', true, ''),
(gen_random_uuid(), '082', 'COND.AV. PROF. DR. AUGUSTO ABREU LOPES, 49', 'AV. PROF. DR. AUGUSTO ABREU LOPES, 49', '', '', true, ''),
(gen_random_uuid(), '083', 'COND PRT ANTÓNIO CORTE REAL, TORRE 3', 'PRT ANTÓNIO CORTE REAL, TORRE 3', '', '', true, ''),
(gen_random_uuid(), '086', 'COND PCTA. CAMILO PESSANHA, Nº 4', 'PCTA. CAMILO PESSANHA, Nº 4', '', '', true, ''),
(gen_random_uuid(), '089', 'COND RUA MALUDA, Nº 8, 10 E 12', 'RUA MALUDA, Nº 8, 10 E 12', '', '', true, ''),
(gen_random_uuid(), '092', 'COND RUA ALVES REDOL, 11', 'RUA ALVES REDOL, 11', '', '', true, ''),
(gen_random_uuid(), '093', 'COND. RUA VALE FORMOSO DE CIMA, 119', 'RUA VALE FORMOSO DE CIMA, 119', '', '', true, ''),
(gen_random_uuid(), '098', 'COND. RUA 4 DE OUTUBRO, Nº. 9', 'RUA 4 DE OUTUBRO, Nº. 9', '', '', true, ''),
(gen_random_uuid(), '100', 'COND. RUA ALMEIDA GARRETT, Nº. 2', 'RUA ALMEIDA GARRETT, Nº. 2', '', '', true, ''),
(gen_random_uuid(), '101', 'COND. RUA D. AFONSO HENRIQUES, 9', 'RUA D. AFONSO HENRIQUES, 9', '', '', true, ''),
(gen_random_uuid(), '108', 'COND. RUA ALZIRA BEATRIZ PACHECO, 16', 'RUA ALZIRA BEATRIZ PACHECO, 16', '', '', true, ''),
(gen_random_uuid(), '110', 'COND. RUA ANTÓNIO SÉRGIO, Nº 4', 'RUA ANTÓNIO SÉRGIO, Nº 4', '', '', true, ''),
(gen_random_uuid(), '121', 'COND. R. BEATRIZ ÂNGELO, Nº 10', 'R. BEATRIZ ÂNGELO, Nº 10', '', '', true, ''),
(gen_random_uuid(), '122', 'AV PROFESSOR DR. AUGUSTO ABREU LOPES Nº61', 'AV PROFESSOR DR. AUGUSTO ABREU LOPES Nº61', '', '', true, ''),
(gen_random_uuid(), '123', 'COND. AV. DAS DESCOBERTAS, 31', 'AV. DAS DESCOBERTAS, 31', '', '', true, ''),
(gen_random_uuid(), '126', 'COND. RUA VALE FORMOSO DE CIMA, 113', 'RUA VALE FORMOSO DE CIMA, 113', '', '', true, ''),
(gen_random_uuid(), '128', 'COND. RUA DR. JAIME CORTESÃO, 15', 'RUA DR. JAIME CORTESÃO, 15', '', '', true, ''),
(gen_random_uuid(), '140', 'COND. RUA AQUILINO RIBEIRO, 3', 'RUA AQUILINO RIBEIRO, 3', '', '', true, ''),
(gen_random_uuid(), '141', 'COND. PCTA JOÃO VILLARET Nº 1', 'PCTA JOÃO VILLARET Nº 1', '', '', true, ''),
(gen_random_uuid(), '142', 'COND. RUA BARTOLOMEU DIAS, 13', 'RUA BARTOLOMEU DIAS, 13', '', '', true, ''),
(gen_random_uuid(), '143', 'COND. RUA ANTONIO SERGIO, 8', 'RUA ANTONIO SERGIO, 8', '', '', true, ''),
(gen_random_uuid(), '144', 'COND. R. DOMINGOS SEQUEIRA, 7', 'R. DOMINGOS SEQUEIRA, 7', '', '', true, ''),
(gen_random_uuid(), '145', 'COND. R.VALE FORMOSO DE CIMA, 97', 'R.VALE FORMOSO DE CIMA, 97', '', '', true, ''),
(gen_random_uuid(), '146', 'COND. PRACETA TEN. CORONEL SALGUEIRO MAIA, 8', 'PRACETA TEN. CORONEL SALGUEIRO MAIA, 8', '', '', true, ''),
(gen_random_uuid(), '147', 'COND. RUA EUGÉNIO DE CASTRO, 6', 'RUA EUGÉNIO DE CASTRO, 6', '', '', true, ''),
(gen_random_uuid(), '148', 'COND. PRACETA MARIA LAMAS, LT 47', 'PRACETA MARIA LAMAS, LT 47', '', '', true, ''),
(gen_random_uuid(), '149', 'COND. RUA. DR. MARIO SACRAMENTO, 13', 'RUA. DR. MARIO SACRAMENTO, 13', '', '', true, ''),
(gen_random_uuid(), '150', 'COND. R. PROFESSOR EGAS MONIZ, 32', 'R. PROFESSOR EGAS MONIZ, 32', '', '', true, ''),
(gen_random_uuid(), '151', 'COND. R. MESTRE AVIZ, 16', 'R. MESTRE AVIZ, 16', '', '', true, ''),
(gen_random_uuid(), '152', 'COND. PRAÇA PAIVA COUCEIRO, 5', 'PRAÇA PAIVA COUCEIRO, 5', '', '', true, ''),
(gen_random_uuid(), '153', 'COND. PRACETA FLORBELA ESPANCA, 9', 'PRACETA FLORBELA ESPANCA, 9', '', '', true, ''),
(gen_random_uuid(), '154', 'COND. CALÇADA DA PALMA DE BAIXO, 29', 'CALÇADA DA PALMA DE BAIXO, 29', '', '', true, ''),
(gen_random_uuid(), '155', 'COND. RUA D. AFONSO HENRIQUES, 33', 'RUA D. AFONSO HENRIQUES, 33', '', '', true, ''),
(gen_random_uuid(), '157', 'COND. RUA DOS OPERÁRIOS, Nº9', 'RUA DOS OPERÁRIOS, Nº9', '', '', true, ''),
(gen_random_uuid(), '158', 'COND. AV.PROF. EGAS MONIZ, 9', 'AV.PROF. EGAS MONIZ, 9', '', '', true, ''),
(gen_random_uuid(), '159', 'COND. AV. DEFENSORES DE CHAVES, Nº43', 'AV. DEFENSORES DE CHAVES, Nº43', '', '', true, ''),
(gen_random_uuid(), '161', 'COND. RUA PADRE AMÉRICO, 12', 'RUA PADRE AMÉRICO, 12', '', '', true, ''),
(gen_random_uuid(), '162', 'COND. RUA VALE FORMOSO DE CIMA, 134', 'RUA VALE FORMOSO DE CIMA, 134', '', '', true, ''),
(gen_random_uuid(), '163', 'COND. R. PEDRO ÁLVARES CABRAL, 1', 'R. PEDRO ÁLVARES CABRAL, 1', '', '', true, ''),
(gen_random_uuid(), '164', 'COND. RUA CABO VERDE, 14', 'RUA CABO VERDE, 14', '', '', true, ''),
(gen_random_uuid(), '165', 'COND. AV. DAS ACÁCIAS, 2', 'AV. DAS ACÁCIAS, 2', '', '', true, ''),
(gen_random_uuid(), '166', 'COND. PRACETA FLORBELA ESPANCA, 7', 'PRACETA FLORBELA ESPANCA, 7', '', '', true, ''),
(gen_random_uuid(), '168', 'COND. R. DA JUVENTUDE, 11', 'R. DA JUVENTUDE, 11', '', '', true, ''),
(gen_random_uuid(), '169', 'COND. RUA NUNO ALVARES PEREIRA, 7', 'RUA NUNO ALVARES PEREIRA, 7', '', '', true, ''),
(gen_random_uuid(), '170', 'COND. R. CHAFARIZ DEL REI, 3', 'R. CHAFARIZ DEL REI, 3', '', '', true, ''),
(gen_random_uuid(), '171', 'COND. R. VÍTOR CORDON, 1', 'R. VÍTOR CORDON, 1', '', '', true, ''),
(gen_random_uuid(), '172', 'COND. AV.DAS ACÁCIAS, 10', 'AV.DAS ACÁCIAS, 10', '', '', true, ''),
(gen_random_uuid(), '173', 'COND. R. DOS OPERÁRIOS, 11', 'R. DOS OPERÁRIOS, 11', '', '', true, ''),
(gen_random_uuid(), '174', 'COND. AV. ELIAS GARCIA, 18', 'AV. ELIAS GARCIA, 18', '', '', true, ''),
(gen_random_uuid(), '175', 'COND. R.AGOSTINHO SILVA, 10', 'R.AGOSTINHO SILVA, 10', '', '', true, ''),
(gen_random_uuid(), '176', 'COND.R.PADRE JOSE ANCHIETA, 4', 'R.PADRE JOSE ANCHIETA, 4', '', '', true, ''),
(gen_random_uuid(), '177', 'COND. RUA VALE FORMOSO DE CIMA, 127', 'RUA VALE FORMOSO DE CIMA, 127', '', '', true, ''),
(gen_random_uuid(), '178', 'COND. PCTA VIRGÍNIA DE CASTRO ALMEIDA,3', 'PCTA VIRGÍNIA DE CASTRO ALMEIDA,3', '', '', true, ''),
(gen_random_uuid(), '179', 'COND. RUA CMD SACADURA CABRAL, 11', 'RUA CMD SACADURA CABRAL, 11', '', '', true, ''),
(gen_random_uuid(), '180', 'COND. PCTA FLORBELA ESPANCA, 2', 'PCTA FLORBELA ESPANCA, 2', '', '', true, '');

-- Insert real supplier data (clean list without duplicates)
INSERT INTO public.suppliers (id, name, email, phone, address, nif, specialization, is_active, admin_notes) VALUES
(22, 'TKE', 'info.tkept@tkelevator.com', '+351 21 43 08 100', 'Sintra Business Park, Edifício 4, 2B, Zona Industrial da Abrunheira, 2710‑089 Sintra', '501 445 226', 'Elevadores', true, ''),
(23, 'Clefta', 'geral@clefta.pt', '(+351) 217 648 435', 'Rua Mariano Pina, 13, Loja B, 1500‑442 Lisboa', '501 324 046', 'Segurança', true, ''),
(24, 'Sr. Obras', 'ana.ferreira.santos@srobras.pt', '961 777 625 / 966 370 189', 'Avenida da República, 6, 7.º Esq., 1050‑191 Lisboa', '509 541 887', 'Construção e Reparações', true, ''),
(25, 'Mestre das Chaves', 'lojamestredaschaves@gmail.com', '939 324 688 / 933 427 963', 'Rua Augusto Gil, 14‑A, 2675‑507 Odivelas (Lisboa)', '506 684 504', 'Serralharia', true, ''),
(26, 'Desinfest Lar', 'desinfestlar@sapo.pt', '+351 219 336 788', 'Largo da Saudade, Vivenda Rosinha, 2675‑260 Odivelas', '502 763 760', 'Controlo de Pragas', true, ''),
(27, 'Ascenso Eleva Lda', 'ascensoeleva.lda@sapo.pt', '+351 219 166 101', 'Rua de Urano, 10‑A, Serra das Minas, 2635‑580 Rio de Mouro – Sintra', '503 077 291', 'Elevadores', true, ''),
(28, 'Ipest', 'geral@ipest.pt', '+351 219 661 404 / 925 422 204', 'Rua Casal dos Ninhos, Nº 2E, Escritório 8, 2665‑536 Venda do Pinheiro', '', 'Controlo de Pragas', true, ''),
(39, 'Andre', 'andre@luvimg.com', '', '', '', '', true, ''),
(40, 'bilal machraa', 'bilal.machraa@gmail.com', '918911308', '3 Rua do Regueiro do Tanque', '123456', 'afd', true, 'dafdsf');

-- Insert real intervention types data
INSERT INTO public.intervention_types (id, name, description, category, urgency_level) VALUES
(15, 'Reparação de Fugas de Água (Partes Comuns)', 'Canalização / Hidráulica', 'Canalização', 'urgent'),
(16, 'Desentupimento de Esgotos (Partes Comuns)', 'Canalização / Hidráulica', 'Canalização', 'urgent'),
(17, 'Manutenção de Bombas de Água / Grupo Hidropressor', 'Canalização / Hidráulica', 'Canalização', 'normal'),
(18, 'Reparação/Substituição Coluna de Água', 'Canalização / Hidráulica', 'Canalização', 'urgent'),
(19, 'Leitura/Verificação de Contadores', 'Canalização / Hidráulica', 'Canalização', 'normal'),
(20, 'Reparação de Avaria Elétrica (Partes Comuns)', 'Eletricidade', 'Eletricidade', 'urgent'),
(21, 'Substituição de Lâmpadas/Iluminação (Partes Comuns)', 'Eletricidade', 'Eletricidade', 'normal'),
(22, 'Manutenção Quadro Elétrico Geral', 'Eletricidade', 'Eletricidade', 'normal'),
(23, 'Reparação/Manutenção Videoporteiro/Intercomunicador', 'Eletricidade', 'Eletricidade', 'normal'),
(24, 'Reparação de Fissuras/Infiltrações (Partes Comuns)', 'Construção Civil / Pedreiro', 'Construção Civil', 'urgent'),
(25, 'Impermeabilização (Terraços, Coberturas, Garagens)', 'Construção Civil / Pedreiro', 'Construção Civil', 'normal'),
(26, 'Reparação de Pavimentos (Partes Comuns)', 'Construção Civil / Pedreiro', 'Construção Civil', 'normal'),
(27, 'Pequenas Obras de Conservação', 'Construção Civil / Pedreiro', 'Construção Civil', 'normal'),
(28, 'Pintura de Áreas Comuns (Escadas, Halls)', 'Pinturas', 'Pinturas', 'normal'),
(29, 'Pintura de Fachada', 'Pinturas', 'Pinturas', 'normal'),
(30, 'Pintura de Portas/Grades Comuns', 'Pinturas', 'Pinturas', 'normal'),
(31, 'Reparação/Manutenção Portão de Garagem', 'Serralharia / Automatismos', 'Serralharia', 'urgent'),
(32, 'Reparação/Substituição de Fechaduras (Portas Comuns)', 'Serralharia / Automatismos', 'Serralharia', 'urgent'),
(33, 'Reparação de Grades/Corrimãos', 'Serralharia / Automatismos', 'Serralharia', 'normal'),
(34, 'Manutenção Preventiva de Elevador', 'Elevadores', 'Elevadores', 'normal'),
(35, 'Reparação de Avaria de Elevador', 'Elevadores', 'Elevadores', 'urgent'),
(36, 'Manutenção de Jardins e Espaços Verdes', 'Jardinagem', 'Jardinagem', 'normal'),
(37, 'Manutenção/Reparação Sistema de Rega', 'Jardinagem', 'Jardinagem', 'normal'),
(38, 'Limpeza Geral de Áreas Comuns', 'Limpeza', 'Limpeza', 'normal'),
(39, 'Limpeza de Garagens', 'Limpeza', 'Limpeza', 'normal'),
(40, 'Limpeza de Vidros', 'Limpeza', 'Limpeza', 'normal'),
(41, 'Manutenção/Carregamento de Extintores', 'Segurança e Incêndio', 'Segurança', 'normal'),
(42, 'Manutenção Sistema Deteção Incêndios (SADI)', 'Segurança e Incêndio', 'Segurança', 'normal'),
(43, 'Manutenção Portas Corta-Fogo', 'Segurança e Incêndio', 'Segurança', 'normal'),
(44, 'Manutenção/Reparação CCTV', 'Segurança e Incêndio', 'Segurança', 'normal'),
(45, 'Controlo de Pragas', 'Outros', 'Outros', 'normal'),
(46, 'Limpeza de Caleiras/Algerozes', 'Outros', 'Outros', 'normal'),
(47, 'Verificação/Reparação Antena Coletiva', 'Outros', 'Outros', 'normal'),
(48, 'Pedido de Orçamento', 'Administrativos/Processuais', 'Administrativos', 'normal'),
(49, 'Ativação de Garantia', 'Administrativos/Processuais', 'Administrativos', 'normal'),
(50, 'outros', 'Outros', 'Outros', 'normal'),
(52, 'Manutenção Preventiva', 'Manutenção preventiva regular', 'Manutenção', 'normal'),
(53, 'Reparação de Emergência', 'Reparação urgente necessária', 'Emergência', 'urgent'),
(54, 'Instalação', 'Instalação de novos equipamentos', 'Instalação', 'normal');